import { StyleSheet, Platform, StatusBar, Dimensions } from 'react-native';


const screenWidth = Dimensions.get('window').width;

export const COLORS = {
    PRIMARY: '#4A90E2',
    SECONDARY: '#7B68EE',
    SUCCESS: '#50C878',
    BACKGROUND: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)',
    BACKGROUND_SOLID: '#f8fafc',
    WHITE: '#ffffff',
    TEXT_PRIMARY: '#2d3748',
    TEXT_SECONDARY: '#718096',
    BORDER: 'rgba(226, 232, 240, 0.8)',
    DANGER: '#ff7878ff',
    CARD_SHADOW: 'rgba(0, 0, 0, 0.1)',
    GRADIENT_PRIMARY: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    GRADIENT_SUCCESS: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
    GRADIENT_CARD: 'linear-gradient(145deg, #ffffff 0%, #f8fafc 100%)',
    GLASS_BACKGROUND: 'rgba(255, 255, 255, 0.25)',
    GLASS_BORDER: 'rgba(255, 255, 255, 0.18)',
};

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 25%, #11998e 75%, #38ef7d 100%)',
        paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },

    container: {
        flex: 1,
        backgroundColor: 'transparent',
        paddingBottom: Platform.OS === 'android' ? 20 : 0,
    },

    mainContainer: {
        flex: 1,
        backgroundColor: 'transparent',
    },
    scrollContent: {
        paddingBottom: Platform.OS === 'android' ? 0 : 0, // Spazio extra per navigation
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        backgroundColor: COLORS.GLASS_BACKGROUND,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.GLASS_BORDER,
        shadowColor: COLORS.CARD_SHADOW,
    },
    title: {
        fontSize: 24,
        fontWeight: '800',
        color: COLORS.WHITE,
    },
    viewModeToggle: {
        flexDirection: 'row',
        borderRadius: 25,
        padding: 3,
        borderWidth: 1,
        borderColor: 'rgba(0, 0, 0, 1)',
    },
    toggleButton: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 22,
        minWidth: 80,
        alignItems: 'center',
    },
    activeToggle: {
        elevation: 4,
        backgroundColor: 'rgba(118, 75, 162, 0.3)',
    },
    toggleText: {
        fontSize: 13,
        fontWeight: '600',
        color: 'rgba(255, 255, 255, 1)',
    },
    activeToggleText: {
        color: COLORS.WHITE,
        fontWeight: '700',
    },
    balanceCard: {
        borderRadius: 20,
        margin: 20,
        padding: 25,
        alignItems: 'center',
        borderWidth: 2,
        borderColor: 'rgba(255, 255, 255, 0.9)',
    },
    balanceLabel: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.9)',
        fontWeight: '600',
        textShadow: '0 1px 3px rgba(0,0,0,0.3)',
    },
    balanceAmount: {
        fontSize: 36,
        fontWeight: '900',
        color: COLORS.WHITE,
        marginTop: 8,
        textShadow: '0 2px 4px rgba(0,0,0,0.3)',
        letterSpacing: -1,
    },
    centerContent: {
        justifyContent: 'center',
        flex: 1,
    },
    chartCard: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        marginHorizontal: 20,
        marginTop: 0,
        marginBottom: 20,
        padding: 25,
        borderRadius: 20,
        width: screenWidth - 40,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 1)',
        shadowColor: COLORS.CARD_SHADOW,
    },
    chartTitle: {
        fontSize: 20,
        fontWeight: '700',
        marginBottom: 25,
        textAlign: 'center',
        color: 'white'
    },
    flatListContent: {
        paddingBottom: Platform.OS === 'android' ? 30 : 20,
    },
    HorizontalBarChart: {
        marginBottom: 20,
    },
    barChartContainer: {
        paddingVertical: 15,
    },
    barChartRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 14,
        width: '100%'
    },
    barChartLabel: {
        fontSize: 14,
        color: 'white',
        width: 70,
        marginRight: 12,
        fontWeight: '600',
    },
    barChartRowTrack: {
        flex: 1,
        height: 26,
        borderRadius: 13,
        overflow: 'hidden',
        marginRight: 12,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 1)',
    },
    barChartRowBar: {
        height: '100%',
        borderRadius: 13,
        shadowColor: 'rgba(0, 0, 0, 0.2)',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    barChartPercentage: {
        fontSize: 13,
        fontWeight: 'bold',
        color: 'rgba(255, 255, 255, 0.7)',
        width: 45,
        textAlign: 'right',
    },
    barChartAmount: {
        fontSize: 12,
        fontWeight: '700',
        color: COLORS.WHITE,
        textAlign: 'right',
    },
    percentageOnly: {
        width: 40,
        alignItems: 'flex-end',
    },
    amountAndPercentage: {
        width: 70,
        alignItems: 'flex-end',
    },
    pieRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    pieBarContainer: {
        flex: 1,
        height: 30,
        backgroundColor: '#f0f0f0',
        borderRadius: 15,
        overflow: 'hidden',
        marginRight: 10,
    },
    pieBar: {
        height: '100%',
        borderRadius: 15,
    },
    piePercentage: {
        width: 45,
        fontSize: 14,
        fontWeight: 'bold',
        color: COLORS.TEXT_PRIMARY,
        textAlign: 'right',
    },
    legendContainer: {
        marginTop: 10,
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: COLORS.BORDER,
    },
    legendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
        paddingHorizontal: 5,
    },
    legendColor: {
        width: 16,
        height: 16,
        borderRadius: 8,
        marginRight: 10,
    },
    legendText: {
        flex: 1,
        fontSize: 14,
        color: COLORS.TEXT_PRIMARY,
    },
    legendAmount: {
        fontSize: 14,
        color: COLORS.TEXT_SECONDARY,
        fontWeight: 'bold',
    },
    totalContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 15,
        paddingTop: 15,
        borderTopWidth: 1,
        borderTopColor: COLORS.BORDER,
    },
    totalLabel: {
        fontSize: 16,
        fontWeight: 'bold',
        color: COLORS.TEXT_PRIMARY,
    },
    totalValue: {
        fontSize: 16,
        fontWeight: 'bold',
        color: COLORS.PRIMARY,
    },
    summaryCard: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        margin: 20,
        marginTop: 0,
        padding: 20,
        borderRadius: 16,
        flexDirection: 'row',
        justifyContent: 'space-around',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.9)',
    },
    summaryItem: {
        alignItems: 'center',
        flex: 1,
    },
    summaryLabel: {
        fontSize: 14,
        color: COLORS.WHITE,
        marginBottom: 5,
    },
    summaryValue: {
        fontSize: 18,
        fontWeight: 'bold',
    },
    summaryDivider: {
        width: 1,
        backgroundColor: COLORS.BORDER,
        marginVertical: 5,
    },
    accountsSection: {
        margin: 20,
        marginTop: 0,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: COLORS.WHITE,
    },
    headerButtons: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    manageButton: {
        padding: 8,
        marginRight: 10,
    },
    accountCard: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        padding: 18,
        borderRadius: 16,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.9)',
    },
    accountColor: {
        width: 24,
        height: 24,
        borderRadius: 12,
        marginRight: 16,
        borderWidth: 1,
        borderColor: 'rgba(0, 0, 0, 1)',
    },
    accountInfo: {
        flex: 1,
    },
    accountName: {
        fontSize: 17,
        fontWeight: '700',
        color: COLORS.WHITE,
    },
    accountBalance: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.7)',
        marginTop: 3,
        fontWeight: '500',
    },
    quickActions: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginLeft: 20,
        marginRight: 20,
    },
    backupActions: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginLeft: 20,
        marginRight: 20,
        marginBottom: Platform.OS === 'android' ? 70 : 50, // Maggiore spazio per Android
    },
    transactionActionButton: { // Rinominato da actionButton
        padding: 5,
        marginLeft: 5,
    },
    // Mantenere actionButton per i bottoni delle azioni principali
    actionButton: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        padding: 20,
        borderRadius: 16,
        alignItems: 'center',
        width: '45%',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.9)',
    },
    actionText: {
        fontSize: 14,
        color: COLORS.WHITE,
        marginTop: 5,
        textAlign: 'center',
    },
    accountHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        backgroundColor: COLORS.GLASS_BACKGROUND,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.GLASS_BORDER,
        shadowColor: COLORS.CARD_SHADOW,
    },
    accountTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: COLORS.WHITE,
        flex: 1,
        textAlign: 'center',
    },
    transactionsSection: {
        flex: 1,
        margin: 20,
    },
    transactionsList: {
        flex: 1,
    },
    transactionItem: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        padding: 16,
        borderRadius: 14,
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.9)',
    },
    transactionInfo: {
        flex: 1,
    },
    transactionDescription: {
        fontSize: 16,
        fontWeight: 'bold',
        color: COLORS.WHITE,
    },
    transactionDate: {
        fontSize: 12,
        color: COLORS.WHITE,
        marginTop: 2,
    },
    transactionActions: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    transactionAmount: {
        fontSize: 16,
        fontWeight: 'bold',
        marginRight: 10,
        borderstyle: 'solid',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalOverlayNext: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalWrapper: {
        width: '90%',
        backgroundColor: 'rgba(255,255,255,0.6)',
        borderRadius: 20,
        marginVertical: 40,
        padding: 25,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.9)',
    },
    modalContent: {
        flexGrow: 1,
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: '800',
        backgroundClip: 'text',
        color: COLORS.TEXT_PRIMARY,
        marginBottom: 25,
        textAlign: 'center',
    },
    input: {
        borderWidth: 2,
        borderColor: 'rgba(0, 0, 0, 1)',
        borderRadius: 12,
        padding: 15,
        marginBottom: 18,
        fontSize: 16,
        backgroundColor: 'rgba(255, 255, 255, 0.6)',
    },
    labelText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: COLORS.TEXT_PRIMARY,
        marginBottom: 5,
    },
    labelTextSuggerimento: {
        fontSize: 14,
        color: COLORS.TEXT_PRIMARY,
        marginBottom: 10,
        fontStyle: 'italic',
    },
    colorPicker: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: 10,
    },
    colorOption: {
        width: 40,
        height: 40,
        borderRadius: 20,
        margin: 5,
        borderWidth: 1,
    },
    selectedColor: {
        borderWidth: 2,
        borderColor: COLORS.WHITE,
    },
    modalButtonsSingle: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
    },
    modalButtonsDouble: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 10,
    },
    button: {
        width: '47%',
        padding: 8,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelButton: {
        backgroundColor: 'rgba(255, 0, 0, 0.55)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.9)',
    },
    confirmButton: {
        backgroundColor: 'rgba(0, 25, 218, 0.55)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.9)',
    },
    cancelButtonText: {
        color: COLORS.WHITE,
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    confirmButtonText: {
        color: COLORS.WHITE,
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    accountSelector: {
        marginBottom: 20,
    },
    accountOption: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderRadius: 8,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: 'rgba(0, 0, 0, 1)',
        backgroundColor: 'rgba(255,255,255,0.6)',
    },
    selectedAccount: {
        backgroundColor: '#e3f2fd',
        borderWidth: 2,
        borderColor: COLORS.PRIMARY,
    },
    accountOptionText: {
        fontSize: 16,
        color: COLORS.TEXT_PRIMARY,
        marginLeft: 10,
    },
    salarySelector: {
        marginBottom: 20,
    },
    salaryOption: {
        padding: 12,
        borderRadius: 8,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: 'rgba(0, 0, 0, 1)',
        backgroundColor: 'rgba(255,255,255,0.6)',
    },
    selectedSalary: {
        backgroundColor: '#e3f2fd',
        borderWidth: 2,
        borderColor: COLORS.PRIMARY,
    },
    salaryOptionText: {
        fontSize: 16,
        color: COLORS.TEXT_PRIMARY,
    },
    salaryInfo: {
        fontSize: 16,
        color: COLORS.TEXT_SECONDARY,
        textAlign: 'center',
        marginBottom: 10,
        padding: 10,
        backgroundColor: COLORS.BACKGROUND,
        borderRadius: 8,
    },
    remainingInfo: {
        fontSize: 14,
        color: COLORS.SUCCESS,
        textAlign: 'center',
        marginBottom: 20,
        fontWeight: 'bold',
    },
    allocationList: {
        maxHeight: 200,
        marginBottom: 20,
    },
    allocationItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
    },
    allocationInfo: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    allocationName: {
        fontSize: 16,
        color: COLORS.TEXT_PRIMARY,
        marginLeft: 10,
    },
    allocationInput: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 8,
        padding: 8,
        width: 80,
        textAlign: 'center',
        fontSize: 16,
    },
    salaryList: {
        maxHeight: 300,
        marginBottom: 20,
    },
    salaryItem: {
        backgroundColor: 'rgba(255,255,255,0.6)',
        padding: 15,
        borderRadius: 8,
        marginBottom: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(0, 0, 0, 1)',
    },
    selectedSalaryItem: {
        backgroundColor: '#e3f2fd',
        borderWidth: 2,
        borderColor: COLORS.PRIMARY,
    },
    salaryItemName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: COLORS.TEXT_PRIMARY,
    },
    salaryItemAmount: {
        fontSize: 16,
        color: COLORS.TEXT_SECONDARY,
    },
    manageList: {
        maxHeight: 300,
        marginBottom: 20,
    },
    manageItem: {
        padding: 15,
        borderRadius: 20,
        marginBottom: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.6)',
        borderWidth: 1,
        borderColor: 'rgba(0, 0, 0, 1)',
    },
    manageItemInfo: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    manageItemText: {
        flex: 1,
    },
    manageItemName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: COLORS.TEXT_PRIMARY,
    },
    manageItemBalance: {
        fontSize: 14,
        color: COLORS.TEXT_SECONDARY,
        marginTop: 2,
    },
    deleteButton: {
        padding: 8,
        marginLeft: 10,
    },
    emptyText: {
        fontSize: 16,
        color: '#999',
        textAlign: 'center',
        paddingVertical: 20,
    },
    separator: {
        height: 2,
        backgroundColor: '#ccc',
        width: '90%',
        margin: 20,
        alignSelf: 'center',
    },
    manageItemActions: {
        flexDirection: 'row',
        gap: 10,
    },
    editButton: {
        padding: 5,
    },
    modalSubtitle: {
        fontSize: 14,
        color: COLORS.TEXT_SECONDARY,
        textAlign: 'center',
    },
    reallocationList: {
        maxHeight: 300,
    },
    reallocationItem: {
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        marginBottom: 10,
    },
    reallocationInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    reallocationName: {
        fontSize: 16,
        fontWeight: '500',
    },
    reallocationBalance: {
        fontSize: 12,
        color: COLORS.TEXT_SECONDARY,
        flexShrink: 1,
        flexWrap: 'wrap',
        maxWidth: 150, // o una dimensione adatta
    },
    reallocationHeader: {
        paddingBottom: 10,
        borderBottomColor: COLORS.BORDER,
    },
    reallocationTotal: {
        fontSize: 16,
        fontWeight: 'bold',
        color: COLORS.PRIMARY,
        textAlign: 'center',
    },
    reallocationSourceInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    reallocationSourceText: {
        flex: 1,
        marginLeft: 10,
    },
    reallocationInputSection: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    reallocationInputContainer: {
        marginVertical: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
    },
    reallocationInputLabel: {
        fontSize: 14,
        color: COLORS.TEXT_SECONDARY,
        fontWeight: 'bold',
    },
    targetAccountSelector: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    targetAccountOption: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 8,
        backgroundColor: COLORS.BACKGROUND,
        marginRight: 8,
        marginBottom: 8,
    },
    selectedTargetAccount: {
        backgroundColor: '#e3f2fd',
        borderWidth: 1,
        borderColor: COLORS.PRIMARY,
    },
    reallocationSeparator: {
        height: 1,
        backgroundColor: COLORS.BORDER,
        marginTop: 16,
    },
    reallocationTargetContainer: {
        marginTop: 10,
        marginBottom: 10,
    },
    targetAccountText: {
        fontSize: 14,
        marginLeft: 8,
        color: COLORS.TEXT_PRIMARY,
    },
    reallocationTotals: {
        marginTop: 10,
        marginBottom: 10,
        padding: 12,
        backgroundColor: COLORS.BACKGROUND,
        borderRadius: 8,
        justifyContent: 'center',   // centra verticalmente
        alignItems: 'center',       // centra orizzontalmente
    },
    reallocationAccountHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    reallocationAccountInfo: {
        marginLeft: 12,
        flex: 1,
    },
    reallocationAccountName: {
        fontSize: 16,
        fontWeight: '600',
        color: COLORS.TEXT_PRIMARY,
    },
    reallocationAccountBalance: {
        fontSize: 14,
        color: COLORS.TEXT_SECONDARY,
        marginTop: 2,
    },
    reallocationInput: {
        borderWidth: 1,
        borderColor: COLORS.BORDER,
        borderRadius: 8,
        padding: 10,
        fontSize: 16,
        backgroundColor: COLORS.WHITE,
        width: 80,
        textAlign: 'center'
    },
    maxButton: {
        backgroundColor: COLORS.PRIMARY,
        borderRadius: 8,
        fontSize: 16,
        padding: 10,
        width: 60,
    },
    maxButtonText: {
        color: COLORS.WHITE,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    validationError: {
        color: COLORS.DANGER,
        fontSize: 12,
        marginTop: 4,
        fontStyle: 'italic',
    },
});